name: casoon-helpdesk

services:
  api:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  web:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker-imap:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker-mailer:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    restart: always
